import { Poppins } from "next/font/google";
import "./globals.css";
import NextUIprovider from "../components/NextUIprovider";
import { AntdRegistry } from "@ant-design/nextjs-registry";

const font = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "700"],
});

export const metadata = {
  title: "QR ANGADI",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={font.className}>
      <body className='scrollbar-hide md:scrollbar-default sm:scrollbar-default lg:scrollbar-default'>
        <AntdRegistry>

          <NextUIprovider children={children} />
        </AntdRegistry>
      </body>
    </html>
  );
}
