import { Poppins } from "next/font/google";
import "./globals.css";
import NextUIprovider from "../Components/NextUIprovider";

const font = Poppins({ subsets: ["latin"] ,weight:['100','200','300','400','500','700']});

export const metadata = {
  title: "QR ANGADI",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={font.className}>
      <body className="">
        <NextUIprovider children={children} />
      </body>
    </html>
  );
}
